# Generated by Django 4.0.5 on 2022-07-03 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0003_work_weighting_alter_work_unit_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='名稱')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.quotation')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.work')),
            ],
        ),
    ]
