# Generated by Django 4.0.5 on 2022-07-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='amount',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='數量'),
        ),
    ]
