# Generated by Django 4.0.5 on 2022-07-28 17:53

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0015_remove_work_layer3_alter_work_layer2'),
        ('quotation', '0003_quotationitem_layer1_quotationitem_layer2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotation',
            options={'verbose_name': '報價單', 'verbose_name_plural': '報價單'},
        ),
        migrations.AlterModelOptions(
            name='quotationitem',
            options={'verbose_name': '報價項目', 'verbose_name_plural': '報價項目'},
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='layer3',
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='layer2',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='layer1', chained_model_field='layer1', null=True, on_delete=django.db.models.deletion.CASCADE, to='work.layer2', verbose_name='第二層'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='work',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='layer2', chained_model_field='layer2', null=True, on_delete=django.db.models.deletion.CASCADE, to='work.work', verbose_name='項目'),
        ),
    ]
