# Generated by Django 4.0.5 on 2022-07-28 19:39

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('work', '0020_alter_layer1_options_alter_layer2_options_and_more'),
        ('quotation', '0004_alter_quotation_options_alter_quotationitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='客戶'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='layer1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work.layer1', verbose_name='所屬工程'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='layer2',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='layer1', chained_model_field='layer1', null=True, on_delete=django.db.models.deletion.CASCADE, to='work.layer2', verbose_name='分類'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotation.quotation'),
        ),
    ]
