# Generated by Django 4.0.5 on 2022-08-04 09:59

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0022_case_alter_space_type_space_case'),
        ('quotation', '0005_quotation_customer_alter_quotationitem_layer1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='customer',
        ),
        migrations.AddField(
            model_name='quotation',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.case', verbose_name='所屬案件'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='備註'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='quote_date',
            field=models.DateField(blank=True, null=True, verbose_name='報價日期'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='version',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='版本'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='space',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='quotation__case', chained_model_field='case', null=True, on_delete=django.db.models.deletion.CASCADE, to='work.space', verbose_name='空間'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='layer1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work.layer1', verbose_name='工種'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotation.quotation', verbose_name='報價單'),
        ),
    ]
