# Generated by Django 4.0.5 on 2022-08-04 10:15

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0022_case_alter_space_type_space_case'),
        ('quotation', '0006_remove_quotation_customer_quotation_case_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='name',
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work.case', verbose_name='案件'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='space',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='case', chained_model_field='case', null=True, on_delete=django.db.models.deletion.CASCADE, to='work.space', verbose_name='空間'),
        ),
    ]
