# Generated by Django 4.0.5 on 2022-08-07 09:54

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_alter_providerwork_work'),
        ('quotation', '0012_alter_quotationitem_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='provider_work',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='work', chained_model_field='providers', null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.providerwork', verbose_name='施作廠商'),
        ),
    ]
