# Generated by Django 4.0.5 on 2022-08-07 10:21

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0013_quotationitem_provider_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='provider_work',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='work', chained_model_field='work', null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.providerwork', verbose_name='施作廠商'),
        ),
    ]
