# Generated by Django 4.0.5 on 2022-09-21 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('quotation', '0015_alter_quotationitem_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation', to='cases.case', verbose_name='所屬案件'),
        ),
    ]
