# Generated by Django 4.0.5 on 2022-09-21 10:42

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0032_alter_vendorwork_vendor'),
        ('quotation', '0016_alter_quotation_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='provider_work',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='work', chained_model_field='work', null=True, on_delete=django.db.models.deletion.CASCADE, to='work.vendorwork', verbose_name='施作廠商'),
        ),
    ]
