# Generated by Django 4.0.5 on 2022-09-21 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0018_alter_quotationitem_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotationitem',
            old_name='provider_work',
            new_name='vendor_work',
        ),
    ]
