# Generated by Django 4.0.5 on 2022-09-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0019_rename_provider_work_quotationitem_vendor_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='design_fee',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='設計費'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='discount_amount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='折扣額'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='discount_code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='優惠碼'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='extra_tax_percentage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='稅金費率（%）'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='supervise_fee',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='監管費'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='valid_until_date',
            field=models.DateField(blank=True, null=True, verbose_name='效期日（包含）'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='weighting',
            field=models.FloatField(default=1.2, null=True, verbose_name='乘數'),
        ),
    ]
