# Generated by Django 4.0.5 on 2022-07-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='廠商名稱')),
            ],
            options={
                'verbose_name': '廠商',
                'verbose_name_plural': '廠商',
            },
        ),
    ]
