# Generated by Django 4.0.5 on 2022-08-04 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0022_case_alter_space_type_space_case'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='address',
            field=models.CharField(max_length=20, null=True, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='provider',
            name='contact_number',
            field=models.CharField(max_length=20, null=True, verbose_name='聯絡電話'),
        ),
        migrations.AddField(
            model_name='provider',
            name='contact_person',
            field=models.CharField(max_length=20, null=True, verbose_name='聯絡人'),
        ),
        migrations.AddField(
            model_name='provider',
            name='tax_number',
            field=models.CharField(max_length=20, null=True, verbose_name='統編'),
        ),
        migrations.CreateModel(
            name='ProviderWorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.PositiveSmallIntegerField(blank=True, default=100, null=True, verbose_name='單價')),
                ('note', models.TextField(verbose_name='備註')),
                ('active', models.BooleanField(default=True, null=True, verbose_name='有效')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.work')),
            ],
            options={
                'verbose_name': '廠商可施工項目',
                'verbose_name_plural': '廠商可施工項目',
            },
        ),
    ]
