# Generated by Django 4.0.5 on 2022-08-07 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0023_alter_case_address_alter_case_case_number_and_more'),
        ('providers', '0002_provider_address_provider_contact_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProviderWorkItem',
            new_name='ProviderWork',
        ),
    ]
