# Generated by Django 4.0.5 on 2022-08-07 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0023_alter_case_address_alter_case_case_number_and_more'),
        ('providers', '0003_rename_providerworkitem_providerwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerwork',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='work.work'),
        ),
    ]
