# Generated by Django 4.0.5 on 2022-08-07 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0023_alter_case_address_alter_case_case_number_and_more'),
        ('providers', '0004_alter_providerwork_work'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='providerwork',
            options={'verbose_name': '廠商施作項目', 'verbose_name_plural': '廠商施作項目'},
        ),
        migrations.AddField(
            model_name='providerwork',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='providers.provider', verbose_name='報價廠商'),
        ),
        migrations.AlterField(
            model_name='providerwork',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='備註'),
        ),
        migrations.AlterField(
            model_name='providerwork',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='work.work', verbose_name='施作項目'),
        ),
    ]
