# Generated by Django 4.0.5 on 2022-08-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_alter_providerwork_options_providerwork_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerwork',
            name='active',
            field=models.BooleanField(default=True, verbose_name='有效'),
        ),
    ]
