# Generated by Django 4.0.5 on 2022-09-21 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='類型名稱')),
            ],
            options={
                'verbose_name': '空間類型',
                'verbose_name_plural': '      空間類型',
            },
        ),
        migrations.CreateModel(
            name='SpaceName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='空間名稱')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='space_settings.spacetype', verbose_name='空間類型')),
            ],
            options={
                'verbose_name': '空間名稱',
                'verbose_name_plural': '      空間名稱',
            },
        ),
    ]
