# Generated by Django 4.0.5 on 2022-09-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': '案件', 'verbose_name_plural': '案件'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '業主', 'verbose_name_plural': '業主'},
        ),
        migrations.AddField(
            model_name='case',
            name='case_number',
            field=models.CharField(max_length=30, null=True, verbose_name='案號'),
        ),
        migrations.AlterField(
            model_name='case',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='案名'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='聯絡方式'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='業主'),
        ),
    ]
