# Generated by Django 4.0.5 on 2022-07-24 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layer1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='第一層')),
            ],
        ),
        migrations.CreateModel(
            name='Layer2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='第二層')),
                ('belong_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.layer1', verbose_name='所屬')),
            ],
        ),
        migrations.CreateModel(
            name='Layer3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='第三層')),
                ('belong_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.layer2', verbose_name='所屬')),
            ],
        ),
        migrations.CreateModel(
            name='Layer4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='第四層')),
                ('belong_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.layer3', verbose_name='所屬')),
            ],
        ),
    ]
