# Generated by Django 4.0.5 on 2022-07-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_unit_layer3_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer3',
            name='unit_price',
            field=models.PositiveSmallIntegerField(default=100, null=True, verbose_name='單價'),
        ),
        migrations.AddField(
            model_name='layer3',
            name='weighting',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='乘數'),
        ),
    ]
