# Generated by Django 4.0.5 on 2022-07-27 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_layer3_unit_price_layer3_weighting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='廠商名稱')),
            ],
            options={
                'verbose_name': '廠商',
                'verbose_name_plural': '廠商',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='工程名稱')),
            ],
            options={
                'verbose_name': '工程項目',
                'verbose_name_plural': '工程項目',
            },
        ),
        migrations.AlterModelOptions(
            name='layer3',
            options={'verbose_name': '工程項目', 'verbose_name_plural': '工程項目'},
        ),
        migrations.AddField(
            model_name='layer3',
            name='layer1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.layer1', verbose_name='第一層'),
        ),
        migrations.AlterField(
            model_name='layer3',
            name='belong_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.layer2', verbose_name='第二層'),
        ),
        migrations.AlterField(
            model_name='layer3',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='工程名稱'),
        ),
        migrations.AlterField(
            model_name='layer3',
            name='weighting',
            field=models.FloatField(blank=True, default=1.2, null=True, verbose_name='乘數'),
        ),
    ]
