# Generated by Django 4.0.5 on 2022-07-27 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_provider_work_alter_layer3_options_layer3_layer1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Work',
        ),
    ]
