# Generated by Django 4.0.5 on 2022-07-27 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_delete_work'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Layer3',
            new_name='Work',
        ),
    ]
