# Generated by Django 4.0.5 on 2022-07-27 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_rename_layer3_work'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Layer4',
        ),
    ]
