# Generated by Django 4.0.5 on 2022-07-27 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_delete_layer4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='belong_to',
            new_name='layer2',
        ),
        migrations.CreateModel(
            name='Layer3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='第三層')),
                ('belong_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.layer2', verbose_name='所屬')),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='layer3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.layer3', verbose_name='第三層'),
        ),
    ]
