# Generated by Django 4.0.5 on 2022-07-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_rename_belong_to_work_layer2_layer3_work_layer3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layer1',
            options={'verbose_name': '第一層', 'verbose_name_plural': '第一層'},
        ),
        migrations.AlterModelOptions(
            name='layer2',
            options={'verbose_name': '第二層', 'verbose_name_plural': '第二層'},
        ),
        migrations.AlterModelOptions(
            name='layer3',
            options={'verbose_name': '第三層', 'verbose_name_plural': '第三層'},
        ),
        migrations.AlterField(
            model_name='layer1',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='名稱'),
        ),
    ]
