# Generated by Django 4.0.5 on 2022-07-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_alter_layer1_options_alter_layer2_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer2',
            name='belong_to',
        ),
        migrations.AddField(
            model_name='layer2',
            name='belong_to',
            field=models.ManyToManyField(null=True, to='work.layer1', verbose_name='所屬'),
        ),
    ]
