# Generated by Django 4.0.5 on 2022-07-27 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_remove_layer2_belong_to_layer2_belong_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer1',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='名稱'),
        ),
        migrations.AlterField(
            model_name='layer2',
            name='belong_to',
            field=models.ManyToManyField(blank=True, to='work.layer1', verbose_name='所屬'),
        ),
        migrations.AlterField(
            model_name='layer3',
            name='belong_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work.layer2', verbose_name='所屬'),
        ),
        migrations.AlterField(
            model_name='work',
            name='layer1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work.layer1', verbose_name='第一層'),
        ),
        migrations.AlterField(
            model_name='work',
            name='layer2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work.layer2', verbose_name='第二層'),
        ),
        migrations.AlterField(
            model_name='work',
            name='layer3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work.layer3', verbose_name='第三層'),
        ),
        migrations.AlterField(
            model_name='work',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work.unit', verbose_name='單位'),
        ),
        migrations.AlterField(
            model_name='work',
            name='unit_price',
            field=models.PositiveSmallIntegerField(blank=True, default=100, null=True, verbose_name='單價'),
        ),
    ]
