# Generated by Django 4.0.5 on 2022-07-28 15:39

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0011_alter_layer1_name_alter_layer2_belong_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='layer2',
        ),
        migrations.AddField(
            model_name='work',
            name='layer2',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='layer1', chained_model_field='belong_to', horizontal=True, null=True, to='work.layer2', verbose_name='第二層'),
        ),
    ]
