# Generated by Django 4.0.5 on 2022-07-28 17:12

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0012_remove_work_layer2_work_layer2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='layer2',
        ),
        migrations.AddField(
            model_name='work',
            name='layer2',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='layer1', chained_model_field='belong_to', null=True, on_delete=django.db.models.deletion.CASCADE, to='work.layer2', verbose_name='第二層'),
        ),
    ]
