# Generated by Django 4.0.5 on 2022-07-28 17:53

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0014_rename_belong_to_layer2_layer1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='layer3',
        ),
        migrations.AlterField(
            model_name='work',
            name='layer2',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='layer1', chained_model_field='layer1', null=True, on_delete=django.db.models.deletion.CASCADE, to='work.layer2', verbose_name='第二層'),
        ),
    ]
