# Generated by Django 4.0.5 on 2022-07-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0015_remove_work_layer3_alter_work_layer2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Provider',
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': '單位', 'verbose_name_plural': '單位'},
        ),
        migrations.AlterField(
            model_name='layer2',
            name='layer1',
            field=models.ManyToManyField(blank=True, to='work.layer1', verbose_name='所屬第一層'),
        ),
        migrations.AlterField(
            model_name='layer2',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='名稱'),
        ),
    ]
