# Generated by Django 4.0.5 on 2022-07-28 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0017_remove_layer2_layer1_layer2_layer1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layer1',
            options={'verbose_name': '第一層', 'verbose_name_plural': '      第一層'},
        ),
        migrations.AlterModelOptions(
            name='layer2',
            options={'verbose_name': ' 第二層', 'verbose_name_plural': '    第二層'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': '工程項目', 'verbose_name_plural': ' 工程項目'},
        ),
    ]
