# Generated by Django 4.0.5 on 2022-07-28 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0018_alter_layer1_options_alter_layer2_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='layer1',
        ),
        migrations.AlterField(
            model_name='work',
            name='layer2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work.layer2', verbose_name='第二層'),
        ),
    ]
