# Generated by Django 4.0.5 on 2022-07-28 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0019_remove_work_layer1_alter_work_layer2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layer1',
            options={'verbose_name': '所屬工程', 'verbose_name_plural': '      所屬工程'},
        ),
        migrations.AlterModelOptions(
            name='layer2',
            options={'verbose_name': ' 分類', 'verbose_name_plural': '    分類'},
        ),
        migrations.AlterField(
            model_name='layer2',
            name='layer1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work.layer1', verbose_name='所屬工程'),
        ),
        migrations.AlterField(
            model_name='work',
            name='layer2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work.layer2', verbose_name='分類'),
        ),
        migrations.AlterField(
            model_name='work',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='項目名稱'),
        ),
    ]
