# Generated by Django 4.0.5 on 2022-08-04 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0020_alter_layer1_options_alter_layer2_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='名稱')),
            ],
            options={
                'verbose_name': '空間分類',
                'verbose_name_plural': '      空間分類',
            },
        ),
        migrations.AlterModelOptions(
            name='layer1',
            options={'verbose_name': '工種', 'verbose_name_plural': '      工種'},
        ),
        migrations.AlterModelOptions(
            name='layer2',
            options={'verbose_name': ' 工種分類', 'verbose_name_plural': '    工種分類'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': '施工項目', 'verbose_name_plural': ' 施工項目'},
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='名稱')),
                ('area', models.PositiveSmallIntegerField(null=True, verbose_name='坪數')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.spacetype', verbose_name='類別')),
            ],
            options={
                'verbose_name': '空間',
                'verbose_name_plural': '      空間',
            },
        ),
    ]
