# Generated by Django 4.0.5 on 2022-09-21 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0023_alter_case_address_alter_case_case_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='space',
            options={'verbose_name': '物件空間', 'verbose_name_plural': '      物件空間'},
        ),
        migrations.AlterModelOptions(
            name='spacetype',
            options={'verbose_name': '空間類型', 'verbose_name_plural': '      空間類型'},
        ),
        migrations.RemoveField(
            model_name='space',
            name='name',
        ),
        migrations.AlterField(
            model_name='space',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.case', verbose_name='所屬物件'),
        ),
        migrations.AlterField(
            model_name='space',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.spacetype', verbose_name='空間類型'),
        ),
    ]
