# Generated by Django 4.0.5 on 2022-09-21 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0024_alter_space_options_alter_spacetype_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpaceType',
            new_name='SpaceName',
        ),
    ]
