# Generated by Django 4.0.5 on 2022-09-21 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0027_remove_space_type_space_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacename',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work.spacetype', verbose_name='空間類型'),
        ),
        migrations.DeleteModel(
            name='Layer3',
        ),
    ]
