# Generated by Django 4.0.5 on 2022-09-21 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0015_alter_quotationitem_space'),
        ('work', '0028_alter_spacename_type_delete_layer3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spacename',
            name='type',
        ),
        migrations.DeleteModel(
            name='Space',
        ),
        migrations.DeleteModel(
            name='SpaceName',
        ),
        migrations.DeleteModel(
            name='SpaceType',
        ),
    ]
