# Generated by Django 4.0.5 on 2022-09-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0029_remove_spacename_type_delete_space_delete_spacename_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layer1',
            options={'verbose_name': '工種名稱', 'verbose_name_plural': '      工種名稱'},
        ),
        migrations.AlterField(
            model_name='layer1',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='工種名稱'),
        ),
    ]
