# Generated by Django 4.0.5 on 2022-09-21 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        ('work', '0031_vendorwork_delete_case_alter_work_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorwork',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor', verbose_name='施作廠商'),
        ),
    ]
