# Generated by Django 4.0.5 on 2022-09-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0032_alter_vendorwork_vendor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorwork',
            options={'verbose_name': '廠商施作項目', 'verbose_name_plural': '廠商施作項目'},
        ),
    ]
