# Generated by Django 4.0.5 on 2022-07-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='名稱')),
                ('unit', models.CharField(blank=True, max_length=10, null=True, verbose_name='單位')),
                ('amount', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='數量')),
                ('unit_price', models.FloatField(blank=True, default=0, null=True, verbose_name='乘數')),
            ],
        ),
    ]
