# Generated by Django 4.0.5 on 2022-07-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_remove_work_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='weighting',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='乘數'),
        ),
        migrations.AlterField(
            model_name='work',
            name='unit_price',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='單價'),
        ),
    ]
