# Generated by Django 4.0.5 on 2022-09-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_work_weighting_alter_work_unit_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_weighting', models.FloatField(default=1.2, null=True, verbose_name='預設乘數')),
            ],
        ),
        migrations.DeleteModel(
            name='Work',
        ),
    ]
