# Generated by Django 4.0.5 on 2022-08-04 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0006_remove_quotation_customer_quotation_case_and_more'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
