# Generated by Django 4.0.5 on 2022-09-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='聯絡電話'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='contact_person',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='聯絡人'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='tax_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='統編'),
        ),
    ]
